# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: pwd
    - run: ls -la
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.1
    - run: pwd
    - run: ls -la
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
